name: build
on:
  push:
    branches: 
      - master
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: sh build-in-docker.sh
    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
        name: book.pdf
        path: review-starter/Voice_UI_Experts_Project.pdf
